# Generated by Django 5.2.8 on 2025-11-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaboresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('imagem_produto', models.ImageField(upload_to='')),
                ('descricao_produto', models.TextField()),
                ('preco_produto', models.FloatField()),
            ],
        ),
    ]
