# Generated by Django 5.2.8 on 2025-11-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saboresmodel',
            name='imagem_produto',
            field=models.ImageField(upload_to='', verbose_name='sabores/'),
        ),
    ]
