# Generated by Django 5.2.8 on 2025-11-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0002_alter_saboresmodel_imagem_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saboresmodel',
            name='imagem_produto',
        ),
    ]
