# Generated by Django 5.2.8 on 2025-11-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0004_saboresmodel_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saboresmodel',
            name='imagem_produto',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/'),
        ),
    ]
