# Generated by Django 5.2.8 on 2025-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0005_alter_saboresmodel_imagem_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saboresmodel',
            name='imagem_produto',
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='embalagem_produto',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/embalagens'),
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='fundo_descricao_produto',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/fundo_descricao'),
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='ingrediente_pendurado_produto',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/ingrediente_pendurado'),
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='letra_musica_produto',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='mascote_dancando_produto',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/mascote'),
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='mascote_letras_produto',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/mascote'),
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='mascote_parado_produto',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/mascote'),
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='tabela_nutricional_produto',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/tabela_nutricional'),
        ),
    ]
