# Generated by Django 5.2.8 on 2025-11-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0006_remove_saboresmodel_imagem_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saboresmodel',
            name='barra_produto',
            field=models.ImageField(blank=True, null=True, upload_to='sabores/barras'),
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='musica_produto',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saboresmodel',
            name='titulo_musica_produto',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saboresmodel',
            name='letra_musica_produto',
            field=models.TextField(blank=True, null=True, verbose_name='sabores/musica'),
        ),
    ]
