# Generated by Django 5.2.8 on 2025-11-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0007_saboresmodel_barra_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saboresmodel',
            name='musica_produto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='sabores/musica'),
        ),
    ]
