# Generated by Django 5.2.8 on 2025-11-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0008_alter_saboresmodel_musica_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saboresmodel',
            name='letra_musica_produto',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saboresmodel',
            name='musica_produto',
            field=models.FileField(blank=True, null=True, upload_to='sabores/musica'),
        ),
    ]
