# Generated by Django 5.2.8 on 2025-11-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0009_alter_saboresmodel_letra_musica_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saboresmodel',
            name='descricao_produto_pequena',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
